/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Leandro
 */
import Controlador.ControladorRegistro;//IMPORTACIÓN DE LA CLASE.
import Modelo.MetodosRegistro;//IMPORTACIÓN DE LA CLASE.
public class GUI_Botones extends javax.swing.JPanel {

    /**
     * Creates new form GUI_Informacion
     */
       
    ControladorRegistro controladorRegistro;//Instacncia 
    MetodosRegistro metodosRedistro;//Instancia.
   
    public GUI_Botones() //METODO CONSTRUCTOR.
    {
        initComponents();
    }
  
    public void agregarEvento(ControladorRegistro controlador) //ESCUCHADOR DE LOS BOTONES PRINCI´PALES.
    {
        this.controladorRegistro = controlador;
        this.btn_Buscar.addActionListener(controlador);
        this.btn_Agregar.addActionListener(controlador);
        this.btn_Modificar.addActionListener(controlador);
        this.btn_Eliminar.addActionListener(controlador);
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Buscar = new javax.swing.JToggleButton();
        btn_Agregar = new javax.swing.JToggleButton();
        btn_Modificar = new javax.swing.JToggleButton();
        btn_Eliminar = new javax.swing.JToggleButton();

        btn_Buscar.setText("Buscar");

        btn_Agregar.setText("Agregar");

        btn_Modificar.setText("Modificar");

        btn_Eliminar.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btn_Buscar)
                .addGap(27, 27, 27)
                .addComponent(btn_Agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Modificar)
                .addGap(18, 18, 18)
                .addComponent(btn_Eliminar)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Buscar)
                    .addComponent(btn_Agregar)
                    .addComponent(btn_Modificar)
                    .addComponent(btn_Eliminar))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_Agregar;
    private javax.swing.JToggleButton btn_Buscar;
    private javax.swing.JToggleButton btn_Eliminar;
    private javax.swing.JToggleButton btn_Modificar;
    // End of variables declaration//GEN-END:variables
}
