/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Leandro
 */
import Controlador.ControladorRegistro;
import Modelo.MetodosRegistro;
public class GUI_Informacion extends javax.swing.JPanel {

    /**
     * Creates new form GUI_Informacion
     */
    ControladorRegistro controladorRegistro;//Instacncia 
    MetodosRegistro metodosRedistro;//Instancia.

    
    public GUI_Informacion() 
    {
        initComponents();
    }
     
    public String[] devolverInformacion() //Metodos DEVOLVER.
    {
        String arreglo[];
        arreglo = new String[4];
        arreglo[0] = this.jt_NumeroRegistro.getText();
        arreglo[1] = this.jt_NombreDueño.getText();
        arreglo[2] = this.jt_CedulaDueño.getText();
        arreglo[3] = this.jt_PlacaAutomovil.getText();
        return arreglo;
    }
    
    public void mostrarInformacion(String arreglo[])// PARAMETRO DESDE LA CLASE MODELO.OBJETO
    {
        this.jt_NumeroRegistro.setText(arreglo[0]);
        this.jt_NombreDueño.setText(arreglo[1]);
        this.jt_CedulaDueño.setText(arreglo[2]);
        this.jt_PlacaAutomovil.setText(arreglo[3]);
    }
    
     public void mostrarInformacionPrederminada()// PARAMETRO DESDE LA CLASE MODELO.OBJETO
    {
        String   arreglo[];
        arreglo = new String[1];
       // String mensaje=metodosRedistro.numero;
        arreglo[0]=""+metodosRedistro.numeroRegistro;
        this.jt_NumeroRegistro.setText(arreglo[0]);
    
     }
    
        public void limpiarInformacion()//Limpia la ventana.
    {
        this.jt_NumeroRegistro.setText("");
        this.jt_NombreDueño.setText("");
        this.jt_CedulaDueño.setText("");
        this.jt_PlacaAutomovil.setText("");
    }

        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_NumeroRegistro = new javax.swing.JLabel();
        jl_NombreDueño = new javax.swing.JLabel();
        jl_CedulaDueño = new javax.swing.JLabel();
        jl_PlacaAutomovil = new javax.swing.JLabel();
        jt_NumeroRegistro = new javax.swing.JTextField();
        jt_NombreDueño = new javax.swing.JTextField();
        jt_CedulaDueño = new javax.swing.JTextField();
        jt_PlacaAutomovil = new javax.swing.JTextField();

        jl_NumeroRegistro.setText("Número de Registro");

        jl_NombreDueño.setText("Nombre de Dueño");

        jl_CedulaDueño.setText("Cédula del Dueño");

        jl_PlacaAutomovil.setText("Placa del Automóvil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_NumeroRegistro, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_NombreDueño, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_CedulaDueño, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_PlacaAutomovil, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jt_PlacaAutomovil)
                    .addComponent(jt_CedulaDueño)
                    .addComponent(jt_NumeroRegistro, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt_NombreDueño, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_NumeroRegistro)
                    .addComponent(jt_NumeroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_NombreDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_NombreDueño))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_CedulaDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_CedulaDueño))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_PlacaAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_PlacaAutomovil))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_CedulaDueño;
    private javax.swing.JLabel jl_NombreDueño;
    private javax.swing.JLabel jl_NumeroRegistro;
    private javax.swing.JLabel jl_PlacaAutomovil;
    private javax.swing.JTextField jt_CedulaDueño;
    private javax.swing.JTextField jt_NombreDueño;
    private javax.swing.JTextField jt_NumeroRegistro;
    private javax.swing.JTextField jt_PlacaAutomovil;
    // End of variables declaration//GEN-END:variables
}
